services:
  db:
    container_name: postify-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
  cache:
    container_name: postify-cache
    image: redis
    ports:
      - "6379:6379"
